name: DeployWorkflow

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: ssh setup
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_P_KEY}}" > ~/.ssh/meinPrivateKey
          chmod 400 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{secrets.EC2_IP}}  >> ~/.ssh/known_hosts

      - name: Create work-test on EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} "mkdir -p ~/work-test"

      - name: Copy info.txt to EC2
        run: |
          scp -i ~/.ssh/meinPrivateKey ./work-test/info.txt ubuntu@${{ secrets.EC2_IP }}:~/work-test/info.txt

      - name: Verify info.txt on EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} "ls -l ~/work-test && head -n1 ~/work-test/info.txt"

      - name: install nginx
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "sudo apt update"
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "sudo apt install nginx -y"

      - name: SSH Connection
        run: |
          scp -i ~/.ssh/meinPrivateKey frontend/index.html ubuntu@${{secrets.EC2_IP}}:/home/ubuntu/index.html
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html"

  docker-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: ssh setup
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_P_KEY}}" > ~/.ssh/meinPrivateKey
          chmod 400 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{secrets.EC2_IP}}  >> ~/.ssh/known_hosts

      - name: install docker
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "sudo apt update"
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "sudo apt install docker.io -y"
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "sudo usermod -aG docker ubuntu"

      - name: start nginx container on ec2 instance
        run: ssh -i ~/.ssh/meinPrivateKey ubuntu@${{secrets.EC2_IP}} "docker run -d -p 8080:80 nginx"
